#! /usr/bin/env bash

BASE_DESIRED_VERSION="4"

if [ "${BASH_VERSINFO:-0}" -lt "${BASE_DESIRED_VERSION}" ] ; then
	printf "bash version ${BASE_DESIRED_VERSION}+ required"
	printf "Your bash version ${BASH_VERSION}"
	return 1
fi

SCRIPTS_PATH="${QUICKTEST_PATH}/scripts"

${QUICKTEST_BASH} "${SCRIPTS_PATH}/quicktest_action" "___KEY_FOR_ACTION___" "$@"
